---
title: Giovana Ansoain
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: ola@giovana.cc
description: Giovana Ansoain Portfolio
baseurl: ''
url: ''
markdown: kramdown
plugins:
- jekyll-feed
sass:
  sass_dir: "/assets/css"
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
