---
title: Giovana Ansoain
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  upload:
    title: Uploads
    output: true
tag:
  title: brading
email: ola@giovana.cc
description: Giovana Ansoain Portfolio
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_keywords: "site, website, front-end, html5, css3, javascript, jquery, seo, otimizacao, performance"
baseurl: ''
url: ''
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: "/assets/css"
  style: compressed
exclude:
- Gemfile
- Gemfile.lock